### ISSUE TITLE
Right angle expansion connector

### ISSUE THREAD

**Issue by ryaneroth** [eduardocasino/kim-1-mtu-motherboard#1]
Have you considered making the expansion connector a right angle connector like the rest on the board, so you could install this in a chassis like Dave's? https://www.youtube.com/watch?v=fMxOWngmy8I

**Comment by eduardocasino** [comment]
Not really. This is meant for a "tabletop" system, like the KIM-4 or the KIMSI.

Anyway, if you are planning to design a chassis for a KIM-1 system, let me know and I can certainly design a backplane for it!

**Comment by ryaneroth** [comment]
Thank you for the offer, I may take you up on it. I have a friend that is a metal fabricator, and I will work with him on building a chassis.  Trying to find higher res images of the chassis Dave has, which looks similar to the one here http://retro.hansotten.nl/6502-sbc/kim-1-manuals-and-software/kim-1-related-hardware/the-computerist/

**Comment by eduardocasino** [comment]
It is the K-1005 card file system. There is some info in page 35 of this document: http://www.6502.org/users/sjgray/computer/mtu/MTU-fall-1980.pdf

**Comment by ryaneroth** [comment]
I just ended up buying 90 degree 44 pin edge connectors so I can mount the motherboard vertically.

I had to order all the PCBs in quantities of 5, so if you are US based, I'd gladly send you one of the motherboards, as a thank you for all your hard work.

I would also like to sell the rest of the PCBs (KIM-1, 6532 adapter, keypad, motherboard, visual memory, RAM/ROM board) online if that is OK with you.
![IMG_0074](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/a21df359-2e07-4510-8102-ff50f9528e90)

**Comment by eduardocasino** [comment]
Looks great. I assume your friend is building a chassis or you're going to have a hard time when you start connecting boards. :)

The motherboard and RAM/ROM are untested!!! I hope you read the warnings and that you ordered knowing what you were doing... My cards are still travelling from China, so I can't guarantee that they will work. At least I can see that the green led is glowing :P

Thanks for your offer, but I'm based in Spain. I don't mind that you sell your excess PCBs, with just a few conditions:

*  Do not sell the motherboard and RAM/ROM until they are tested **and confirmed working!**
*  Please provide links to the repositories in your selling ads
*  The K-1008, KIM-1, 6532 adapter and keypad boards have a **non-commercial license**, so please sell them at cost. The RAM/ROM and motherboard are Open Hardware, so this restriction does not apply but, **again, wait until they are confirmed working!**

**Comment by ryaneroth** [comment]
Yeah, I'll be sketching up plans for a chassis shortly. I found some nice plastic guide rails to support the PCBs once in it.

I'll update you with my build progress as it gets further along. I'm currently waiting on a few parts, but I did verify power and serial were passing through the motherboard, so that is something :) 

lol, yeah I realize they are untested, but at least where I live, the boards are cheap to have made, it is the shipping that is most of the cost. So it was cheaper to just order the untested boards now, along side a different order, and take the risk, then to pay for separate shipping for them down the road.

My plan is to not sell anything until tested :)

I already offered up my spare KIM-1 boards in the PAL-1 user group **after** I completed my build, at cost plus shipping to the buyer, but then thought I should still run selling them by you to be safe: https://groups.google.com/g/pal6502/c/vnEvhhbyzWM

My goal is not to make a profit, but just to see the spare boards get into the hands of people who will use them. 

Separate question; how hard is it to create a interactive BOM for all the different boards, I found it extremely useful while building the KIM-1?

Also, including links to part sources could be helpful for others, if you want to compile a list, I could provide links to the US based sources I used.

**Comment by eduardocasino** [comment]
> I'll update you with my build progress as it gets further along. I'm currently waiting on a few parts, but I did verify power and serial were passing through the motherboard, so that is something :)

Please do, that will spare me some troubleshooting :) I am also very interested to see how the chassis turns out.
 
> lol, yeah I realize they are untested, but at least where I live, the boards are cheap to have made, it is the shipping that is most of the cost. So it was cheaper to just order the untested boards now, along side a different order, and take the risk, then to pay for separate shipping for them down the road.

Same here. I hope I did not make any mistakes, anyway.

> My plan is to not sell anything until tested :)
> 
> I already offered up my spare KIM-1 boards in the PAL-1 user group **after** I completed my build, at cost plus shipping to the buyer, but then thought I should still run selling them by you to be safe: https://groups.google.com/g/pal6502/c/vnEvhhbyzWM
> 
> My goal is not to make a profit, but just to see the spare boards get into the hands of people who will use them.

That is fantastic, thank you!

> Separate question; how hard is it to create a interactive BOM for all the different boards, I found it extremely useful while building the KIM-1?

Really easy, this plugin for KiCad does it all: https://github.com/openscopeproject/InteractiveHtmlBom

I was planning to add them once the builds were tested.
  
> Also, including links to part sources could be helpful for others, if you want to compile a list, I could provide links to the US based sources I used.

OK, will do. I source most of the parts from DigiKey, the rest from Aliexpress (things like switches, connectors or some passives, like resistors or ceramic caps, never ICs, transistors or non-ceramic)

**Comment by ryaneroth** [comment]
Thanks for the KiCad plugin link!

I had good luck with DigiKey and Mouser for sourcing most of the parts, but here are links to a few parts that gave me trouble finding sources for:

1Mhz crystal
https://www.elexp.com/products/12c1mcrystal-1-mhz

7 segment LED
https://www.digikey.com/en/products/detail/nte-electronics-inc/NTE3061/11648117

SRAM
https://www.jameco.com/z/MM2102AN-4-National-Semiconductor-IC-MM2102AN-4-NMOS-SRAM-1024-Bit-1024x1-250ns-DIP-16_2287991.html
https://www.arcade-electronics.com/ProductDetails.asp?ProductCode=NTE-2102


Piher resistor
https://www.electronicsurplus.com/piher-5k043m-resistor-trimming-5k-ohm-package-of-5:

**Comment by ryanrothsonos** [comment]
Just a status update:

1) If I have the 74LS245 installed in the motherboard, my KIM-1 becomes unresponsive

2) I can't seem to get RS232 out on the daughterboard, but I can wire my breadboard RS232 interface to the motherboard pin header and get serial access. My serial interface is based off of Corsham's serial interface schematics, and uses the same ICs.

**Comment by eduardocasino** [comment]
Unfortunately, my boards are still in transit and seem stuck somewhere in the Netherlands, so I can't do any troubleshooting yet. Looks like I've screwed it up this time, though. 

EDIT: I see the problem with the motherboard now and it is bad, the PCB is useless as it is. I've opened [issue #2](https://github.com/eduardocasino/kim-1-mtu-motherboard/issues/2) to address it.

In the meantime, could you please test this workaround?:

- Lift pin 19 of U4 from its socket
- Using dual side tape, fix a 74LS04 upside down (with the legs facing up) next to U4
- Connect GND and +5V pins of the LS04 to the nearest points (the C4 capacitor seems a good place)
- Connect a wire from pin 2 of J6 to pin 1 of the LS04 and another form pin 2 of the LS04 to pin 19 of U4

**Comment by ryaneroth** [comment]
I will try this and look into the RS232 issue over the next couple of days

**Comment by eduardocasino** [comment]
> I will try this and look into the RS232 issue over the next couple of days

Could you please share the schematic of your serial interface?  I'm suspecting swapped RX/TX llnes.

**Comment by ryaneroth** [comment]
I only implemented the serial side of the schematic
![KIM_IO_schematic](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/8bddcedd-1b51-485c-9cfe-704fed02c261)

**Comment by ryaneroth** [comment]
I just realized the BOM for your board calls for a 74LS06, whereas my board is using a 74LS04. I replaced the 06 with an 04, and now the serial interface works.  Was 74LS06 possibly a typo/error?

Also, I am out of 04s now, so I can't test the fix for the motherboard until more arrive in a day or so

**Comment by eduardocasino** [comment]
The 7406 is intentional, for driving the IEC bus. Do not connect anything to the IEC connector with the 04 in place.

I'm travelling right now, I'll check the schematic of the daughterboard as soon as I can. It should work with the 06, maybe a bad chip?

**Comment by ryaneroth** [comment]
Tried a couple of 06s and performed a logic test on one.

**Comment by eduardocasino** [comment]
Is the resistor network in place? The 7406 has open collector outputs and needs the pull-ups.

**Comment by ryaneroth** [comment]
Yep. I’ll dig into it more over the next couple of days.

EDIT:

Looks like some of my resistor networks are isolated, not bussed 🤦

**Comment by eduardocasino** [comment]
> In the meantime, could you please test this workaround?:
> 
> * Lift pin 19 of U4 from its socket
> * Using dual side tape, fix a 74LS04 upside down (with the legs facing up) next to U4
> * Connect GND and +5V pins of the LS04 to the nearest points (the C4 capacitor seems a good place)
> * Connect a wire from pin 2 of J6 to pin 1 of the LS04 and another form pin 2 of the LS04 to pin 19 of U4

It should really be a NAND (see [this update](https://github.com/eduardocasino/kim-1-mtu-motherboard/issues/2#issuecomment-1872841110)), so the workaround would be:

* Lift pin 19 of U4 from its socket
* Using dual side tape, fix a **74LS00** upside down (with the legs facing up) next to U4
* Connect GND and +5V pins of the LS00 to the nearest points (the C4 capacitor seems a good place)
* Connect wires from pin 2 of J6 to pin 1 of the LS00, from pin 2 of J11 to pin 2 of the LS00 and from pin 3 of the LS00 to pin 19 of U4

I've already made the changes to the schematic and PCB, I'm waiting for your test (or my PCBs to arrive, what happens first) to update the repository. I'm also designing a cleaner fix for the motherboard.

**Comment by ryaneroth** [comment]
OK, I had a spare LS00, so I wired it up as directed, and as far as I can tell, it works, at least with having the decode jumper set to the KIM-1. I could actually tuck this bodge under the motherboard, as I have it on stand offs 😄 

![IMG_0076](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/e26b6fa4-961a-42f3-b2d2-dc5dfb132686)

**Comment by eduardocasino** [comment]
Great, that is the expected behaviour!

**Comment by ryaneroth** [comment]
Here are photos of my successful bodge for the curious. Once I seal the pins in 74LS00's socket in epoxy or something, I'll tuck it away.
![IMG_0078](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/131c107f-3f21-4dbd-8157-62842a68592e)
![IMG_0079](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/a9c05416-93fe-4845-bb83-94e55c081757)
![IMG_0080](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/a20fa28d-7e76-4fb2-86b9-46addb58d9b3)

**Comment by ryaneroth** [comment]
My correct network resistors arrived, and I can now confirm that the 7406 works properly on the serial interface

**Comment by eduardocasino** [comment]
My boards finally arrived from JLCPCB and I can confirm that the fix works. I've updated the repository with instructions and I've also designed a small PCB for a cleaner fix.

@ryaneroth , I think you've also built my RAM/ROM card. That works perfectly with the passive backplane, but has a problem with the DECEN handling and RAM from 0x0400 to 0x13FF does not work with this motherboard. The fix is very easy, I'm opening an issue and I'll test it next weekend. Stay tuned!

**Comment by ryaneroth** [comment]
I built the RAM/ROM card and the visible memory card, and I couldn't get either to work in the motherboard.  I do have the passive backplane on its way here, and should have that in a week or so.

**Comment by eduardocasino** [comment]
Have them both working with the fixed motherboard (except for the 0x0400-0x13FF mapping), see [this (lame) video](https://drive.google.com/file/d/1oaX0GMKfqXOhIBJvXa4D3YZYYIWnPy0r/view?usp=sharing)

Start with this setup:

- Insert just the RAM/ROM board into the rightmost slot.
- Set the DECEN jumper of the motherboard to "Ext"
- Ensure that the DECEN and K7 jumpers (J3) in the RAM/ROM card are installed
- Set SW2 and SW3 of the RAM/ROM to "Disabled"
- Set all the switches in SW4 and SW5 to "Enabled"
- Set all the jumpers in J1 and J2 to "RAM"
- Set switch 1 of SW6 to "ON" (Vectors to KIM-1 ROM)

You should see the RAM from 0x2000 to 0xFFF7 and the 6502 vectors from 0xFFFA to 0xFFFF (0xFFF8 and 0xFFF9 are unused and will be 0x00 or 0xFF depending on the ROMs you are using)

**Comment by ryaneroth** [comment]
OK, I've built my MTU expansion card, and the RAM/ROM card works fine with it, so I'll need to reinspect my motherboard for bad connections, etc.

Now I'm onto trying to get my K-1008 to work :)

EDIT:

I've been doing some testing, and it looks like bit one on the motherboard gets stuck as 1:
Write `0b01010101` to a few locations:
```
2000 FF 55.
2001 FF 55.
2002 FF 55.
2003 FF 55.
```
and read it back:
```
2000 55 
2001 55 
2002 55 
2003 55 
```
write `0b10101010` the inverse to a few locations
```
2000 55 AA.
2001 55 AA.
2002 55 AA.
2003 55 AA.
```
and read it back:
```
2000 AB 
2001 AB 
2002 AB 
2003 AB 
```
I can reproduce this 100% of the time, so that's good, right :)
Just got to look for a short on the data bus

EDIT 2:
Despite passing testing with my logic tester, it was a bad 74ls245
Now I just need to get my K-1008 working!

**Comment by ryanrothsonos** [comment]
Having trouble getting the K-1008 working. I am getting a video signal out, but I cannot write to its memory. I believe I have the addressing set correctly.  I have the K-1008 at C000, and I have that range set to off on the ROM/RAM card, or at least I think I do :)

Writing to memory in that range does not work.  So if I have it configured correctly, I'm thinking one of the supporting logic chips isn't working correctly, despite passing on my logic tester (just using a TL866II, so I'm not sure how reliable its results are.)

![IMG_0106](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/42650421/4681cadb-8382-4ee3-8602-e109e58c0a2d)

**Comment by ryaneroth** [comment]
Having trouble getting the K-1008 working. I am getting a video signal out, but I cannot write to its memory. I believe I have the addressing set correctly.  I have the K-1008 at C000, and I have that range set to off on the ROM/RAM card, or at least I think I do :)

Writing to memory in that range does not work.  So if I have it configured correctly, I'm thinking one of the supporting logic chips isn't working correctly, despite passing on my logic tester (just using a TL866II, so I'm not sure how reliable its results are.)

![IMG_0106](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/42650421/4681cadb-8382-4ee3-8602-e109e58c0a2d)

RAM/Rom vector is set to KIM-1
K-1008 dip switches: 2, 4, and 5 are on

**Comment by eduardocasino** [comment]
Before checking anything else, I would start with just the K-1008 on the bus, to rule out any bad interaction between the two boards. Remove the RAM/ROM card and place the K-1008 into the rightmost slot.

The switch settings are correct. I assume that you have done the steps described in [the "First Setup" section of the README](https://github.com/eduardocasino/k-1008-visable-memory-card-replica?tab=readme-ov-file#first-setup). Re-check that step and see if the card works. 

Once you have it working, install the RAM/ROM card into the rightmost slot (P5) and the K-1008 in any other slot. Only one card can control the DECEN and K7 lines, so ensure that jumpers J11 and J12 **are not installed**.

**Comment by ryaneroth** [comment]
Thanks, I should have mentioned that I had tried with and without the ROM/RAM board, and also on the MTU expansion card.  I've verified the voltage at pin 13 on U8 is 1.4v.  I'm going to dig into whether or not there are any patterns in the bits that change when setting the memory at an address.

Thanks again for the help

**Comment by ryanrothsonos** [comment]
OK, so an update on getting my K-1008 working:

1) I do get video output, but it is all garbage
2) All the memory between C000-DFFF **always** returns 0x40
3) The memory values cannot be changed
4) Trying to set the memory via the keypad, instead of serial, results in the value rapidly oscillating between 0x40 and what looks to be 0x98 (0x40 never turns off so 0x98 is the combination of it and another value)
5) I've tested every LS series IC, and replaced all of them, with no change in this behavior
6) I've tested with the motherboard and the backplane, with identical results

I know this is a stretch, but do you have any more suggestions :)

Thanks as always

**Comment by ryaneroth** [comment]
OK, so an update on getting my K-1008 working:

I do get video output, but it is all garbage
All the memory between C000-DFFF always returns 0x40 (or whatever range I assign it to)
The memory values cannot be changed
Trying to set the memory via the keypad, instead of serial, results in the value rapidly oscillating between 0x40 and what looks to be 0x98 (0x40 never turns off so 0x98 is the combination of it and another value)
I've tested every LS series IC, and replaced all of them, with no change in this behavior
I've tested with the motherboard and the backplane, with identical results
I know this is a stretch, but do you have any more suggestions :)

Thanks as always

EDIT:

Writing this out makes me realize there must have been bridged traces somewhere, and sure enough there are some around the memory sockets 🤦‍♂️

**Comment by eduardocasino** [comment]
> Writing this out makes me realize there must have been bridged traces somewhere, and sure enough there are some around the memory sockets 🤦‍♂️

Yes, the solder mask is not very good, as I've tried to keep it as close as possible to the original, so you have to be extra careful with bridged tracks.

Once you have this sorted out, take a picture of the screen so I can tell you if it is what it is supposed to show. It should have a kind of pattern.

**Comment by ryaneroth** [comment]
Progress! I think I cleaned up any shorts, and I can write to memory now.  I am running glitchwork's memory test right now to make sure my memory is good (or that there aren't anymore shorts)
![Screenshot](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/287421d8-22af-4de8-b814-f35bc1f73e40)

Update:
After running the memory test, there looks like I have a bit I can't set (bit 7)
```
Address	Expected	Actual
C009	C9 11001001	89 10001001
C00B	CB 11001011	8B 10001011
C00D	CD 11001101	8D 10001101
C00F	CF 11001111	8F 10001111
C019	D9 11011001	99 10011001
C01B	DB 11011011	9B 10011011
D009	D9 11011001	99 10011001
```

**Comment by eduardocasino** [comment]
Does this happen for the full 8k range?

**Comment by ryaneroth** [comment]
No, every other. Here is the results of setting all the address to FF (this is after swapping a RAM chip)
```
C000 FF 
C001 BF 
C002 FF 
C003 BF 
C004 FF 
C005 BF 
C006 FF 
C007 BF 
C008 BF 
C009 3F 
C00A BF 
C00B BF 
C00C BF 
C00D 3F 
C00E BF 
C00F BF 
```
Likewise further up in memory
```
D000 FF 
D001 BF 
D002 FF 
D003 FF 
D004 FF 
D005 7F 
D006 FF 
D007 FF 
D008 BF 
D009 3F 
D00A BF 
D00B FF 
D00C BF 
D00D 1E 
D00E BF 
D00F BF
```
Filling all memory with FF
![Screenshot](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/613e474b-51d8-40e1-9b18-6d42bea8c84d)

**Comment by eduardocasino** [comment]
OK, inspecting the schematic, these seem the faulty chips:

C001:BF -> ODD, bit 6  --> U37
C008:BF -> EVEN, bit 6 --> U22
C009:3F -> ODD,  bits 7, 6 --> U36, U37
D005:7F -> ODD,  bit 7, --> U36
D00D:1E -> ODD, bits 7, 6, 5, 0 --> U36, U37, U38, U42

So it seems that memory chips U22, U36, U37, U38 and U42 may be faulty

**Comment by ryaneroth** [comment]
I actually think it is around refreshing the DRAM as if I manually keep reading an address it will hold the correct value

**Comment by ryaneroth** [comment]
OK, I think we are getting there 😆 
```
C009 C9 89
C00B CB 8B
C00D CD 8D
C00F CF 8F
C019 D9 99
C01B DB 9B
C01D DD 9D
C01F DF 9F
```
If I am understanding the memory layout correctly, this would mean U37 if the problem chip, but I've replaced it with several chips, including known good ones, so I am guessing there is a connectivity issue, or short.

Update:
Found a tiny solder blob on that chip causing a short, now the memory testis passing.

**Comment by eduardocasino** [comment]
Congrats on your New k-1008!

Did you see my fix to the RAM/ROM board?

**Comment by ryaneroth** [comment]
Ooh, I missed that somehow, thanks for the heads up

I can now fill the screen solid white or black, but it appears that whatever I enter gets repeated. The first image is at boot, the second image is after setting C000-C016 to FF. This doesn't seem like the correct behavior 😄 
I'm thinking maybe something in the counter circuit
![Screenshot](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/0525df02-f099-4fe3-9068-94758bc19554)
![Screenshot](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/74a92145-c14a-42ae-8d52-f55c21208893)

Update:
On further testing it looks like it is only displaying 0xC010 - 0xC01F, over and over

**Comment by eduardocasino** [comment]
I would first look for shorts in the address lines

**Comment by ryaneroth** [comment]
Just an update

1) I spent a solid hour with a microscope looking at traces, I think they are all good
2) I verified with a multimeter that there are no shorts on the address lines on the RAM side of the 74LS158s
3) I have verified that writing to addresses outside of the 16 bytes at 0xC010 - 0xC01F has no affect on the picture, and whatever is written in that range is repeated on the screen

Going to take a break for a while to think about this, but my current thought is that maybe those 16 bytes are being read repeatedly by the output circuit, possibly by a short I have yet to find.

**Comment by eduardocasino** [comment]
Mmmmm... Is it just the display? I mean, does the RAM works correctly as storage?

**Comment by ryaneroth** [comment]
Yep, I meant to include that in my last post, the ram passes testing, and stores data correctly, as in I can write a value and come back and read it later

**Comment by eduardocasino** [comment]
Okay, that narrows down the problem quite a bit. I'll check the schematic to see if I can give you any hints.

**Comment by ryaneroth** [comment]
Actually this is no longer true, I pulled all the RAM when checking the bus for shorts, and after putting it back in, it does not all work 😞 
Odd addresses seem OK, but not evens above D000
Going to test it all again 256 bytes at a time

**Comment by eduardocasino** [comment]
If the RAM worked correctly, and I assume you got it working at some point, then I think the problem must be in the counter that generates the addresses for refreshing the ram chips and, more specifically, to U19. The symptoms you describe are explained if U19A is stuck  at Q0 == 1 and only U19B is counting correctly:

![image](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/37220276/f810bc0d-c2a6-47db-a779-71b7daea48b2)

Check around U19 for shorts and/or replace it.

**Comment by ryaneroth** [comment]
Thanks. I'll dig into this!

**Comment by eduardocasino** [comment]
Just to clarify, the above is correct if the RAM is working OK and the display only displays contents from 0xC010 - 0xC01F over and over. First thing to do is to get the RAM working again.

**Comment by ryaneroth** [comment]
Wow, this is super embarrassing seeing how many hours I spent examining this card.  Pin 9 on U34 was bent outside its socket 😭 🤦 

Thank you again for all your help!

Here is our reward:
![Bender](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/c6d003b6-bc0a-4299-9c02-2d805f333036)

**Comment by eduardocasino** [comment]
Glad you got it working!

I assume the color artifacts are caused by the camera, aren't they?

**Comment by ryaneroth** [comment]
I'm using a USB capture card, and it introduces the color artifacts when it can't hold a good sync

My quick version
![image](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/6cfed4b5-a6eb-4c88-8256-702a37b44b93)
of this
![image](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/67513703/b055391e-ea9c-42d4-98e2-5d2dd1be4d94)

**Comment by eduardocasino** [comment]
Ah, yes, happened to me too with a video to hdmi converter:

![bender_artifacts](https://github.com/eduardocasino/kim-1-mtu-motherboard/assets/37220276/14b70f25-9890-4283-93f9-1eea69c837e4)

**Comment by ryaneroth** [comment]
It works pretty well for costing $25, but I realize a CRT would work better
