### ISSUE TITLE
Data bus transceiver must be put in high impedance state when DECEN is low

### ISSUE THREAD

**Issue by eduardocasino** [eduardocasino/kim-1-mtu-motherboard#2]
The 74LS245 data bus transceiver (U4 in the schematic) is enabled permanently (the OE line is tied to ground) This means that when the KIM-1 is handling the address decoding and the ~R/W line is  low, both the KIM-1 and the transceiver are trying to drive the data bus, which renders the system unusable.

The solution is to disable the transceiver when DECEN is low, so the OE line must be driven by DECEN through an inverter.

Until this is fixed, the board is useless.

**Comment by eduardocasino** [comment]
The transceiver must be disabled also when K7 is low (interrupt vectors pointing to the kim-1 system ROM)

**Comment by ryaneroth** [comment]
I soldered up one of the expansion bus slots, and threw the RAM board on it, and it is working.  RAM test passed.
